# Generated by Django 3.2.22 on 2023-11-24 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('published_year', models.IntegerField()),
                ('language', models.CharField(choices=[('English', 'English'), ('Czech', 'Czech'), ('German', 'German')], default='English', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='media/books/placeholder.placeholder.webp', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='media/books')),
                ('image_alt', models.CharField(blank=True, default='Cover image', max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('key', models.CharField(default='23', max_length=10)),
                ('likes', models.ManyToManyField(blank=True, related_name='book_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(default='contributor', max_length=20)),
                ('city', models.CharField(choices=[('Vienna', 'Vienna'), ('Prague', 'Prague'), ('Dublin', 'Dublin')], max_length=50)),
                ('location', models.CharField(choices=[('by a friend', 'by a friend '), ('to be found', 'to be found')], max_length=20)),
                ('location_hidden', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_contribution', to='books.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
