# Generated by Django 3.2.22 on 2023-10-15 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('published_year', models.IntegerField()),
                ('language', models.CharField(choices=[('en', 'English'), ('cs', 'Czech'), ('de', 'German')], default='en', max_length=10)),
                ('description', models.TextField()),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='media/books')),
                ('image_alt', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='book_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', '-created_on'],
            },
        ),
    ]
