# Generated by Django 3.2.22 on 2023-11-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontribution',
            name='user_status',
            field=models.CharField(choices=[('owner', 'owner'), ('contributor', 'contributor')], default='contributor', max_length=20),
        ),
    ]
