# Generated by Django 3.2.22 on 2023-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontribution',
            name='location',
            field=models.CharField(choices=[('at a friend', 'by a friend '), ('in a hidden place', 'at a hidden place')], max_length=20),
        ),
    ]
