# Generated by Django 3.2.22 on 2023-10-15 12:30

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='media/books/placeholder.placeholder.webp', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='media/books'),
        ),
    ]
