# Generated by Django 3.2.22 on 2023-12-10 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInsertedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_key', models.CharField(max_length=20)),
                ('inserted_on', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inserted_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inserted_on'],
            },
        ),
    ]
