# Generated by Django 3.2.22 on 2023-11-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcontribution',
            name='slug',
        ),
    ]
