# Generated by Django 3.2.22 on 2023-12-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_userinsertedkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_key', models.CharField(max_length=20)),
                ('inserted_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-inserted_on'],
            },
        ),
        migrations.DeleteModel(
            name='UserInsertedKey',
        ),
    ]
