# Generated by Django 3.2.22 on 2023-12-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20231212_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-city']},
        ),
        migrations.AlterField(
            model_name='bookcontribution',
            name='location',
            field=models.CharField(choices=[('at a friend', 'by a friend '), ('in a hidden place', 'at a hidden place'), ('it is my book', 'it is my book')], max_length=20),
        ),
    ]
