# Generated by Django 3.2.22 on 2023-10-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_alt',
            field=models.CharField(default='Placeholder image', max_length=100),
        ),
    ]
