# Generated by Django 3.2.22 on 2023-11-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookcontribution_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontribution',
            name='location',
            field=models.CharField(choices=[('by a friend', 'by a friend '), ('at a hidden place', 'at a hidden place')], max_length=20),
        ),
    ]
