# Generated by Django 3.2.22 on 2023-12-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20231214_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city']},
        ),
    ]
