# Generated by Django 3.2.22 on 2023-11-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookcontribution_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontribution',
            name='location_hidden',
            field=models.TextField(null=True),
        ),
    ]
