# Generated by Django 3.2.22 on 2023-12-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20231210_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ascii_name', models.CharField(blank=True, max_length=200, null=True)),
                ('alternate_names', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_class', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_code', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, max_length=200, null=True)),
                ('cou_name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code_2', models.CharField(blank=True, max_length=200, null=True)),
                ('admin1_code', models.CharField(blank=True, max_length=200, null=True)),
                ('admin2_code', models.CharField(blank=True, max_length=200, null=True)),
                ('admin3_code', models.CharField(blank=True, max_length=200, null=True)),
                ('admin4_code', models.CharField(blank=True, max_length=200, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('elevation', models.CharField(blank=True, max_length=200, null=True)),
                ('dem', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=200, null=True)),
                ('modification_date', models.CharField(blank=True, max_length=200, null=True)),
                ('label_en', models.CharField(blank=True, max_length=200, null=True)),
                ('coordinates_lon', models.FloatField(blank=True, null=True)),
                ('coordinates_lat', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
