# Generated by Django 3.2.22 on 2023-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookcontribution_location_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontribution',
            name='location_hidden',
            field=models.TextField(blank=True, default='missing', null=True),
        ),
    ]
