# Generated by Django 3.2.22 on 2023-10-16 21:09

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='media/books/placeholder.placeholder.webp', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='media/books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_alt',
            field=models.CharField(blank=True, default='Cover image', max_length=100),
        ),
    ]
