# Generated by Django 3.2.22 on 2023-11-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_bookcontribution_book_key_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcontribution',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='bookcontribution',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcontribution',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
