# Generated by Django 3.2.22 on 2023-11-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20231016_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_on', 'title']},
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Czech', 'Czech'), ('German', 'German')], default='en', max_length=10),
        ),
    ]
