# Generated by Django 3.2.22 on 2023-11-30 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_auto_20231130_2107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookcontribution',
            unique_together={('book', 'user')},
        ),
    ]
