# Generated by Django 3.2.22 on 2023-11-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookcontribution_location_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontribution',
            name='book_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_key', to='books.book'),
        ),
    ]
