# Generated by Django 3.2.22 on 2023-11-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookcontribution_book_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontribution',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
