# Generated by Django 3.2.22 on 2023-11-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='key',
            field=models.CharField(default='23', max_length=10),
        ),
    ]
