# Generated by Django 3.2.22 on 2023-11-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20231130_2124'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookcontribution',
            name='unique_user_book_contribution',
        ),
    ]
