# Generated by Django 3.2.22 on 2023-11-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_bookcontribution_unique_user_book_contribution'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookcontribution',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_contribution'),
        ),
    ]
