# Generated by Django 3.2.22 on 2023-11-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20231116_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='key',
            field=models.CharField(default='23', max_length=10),
        ),
    ]
