# Generated by Django 3.2.22 on 2023-12-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_bookcontribution_unique_user_book_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontribution',
            name='slug',
            field=models.SlugField(default='x2'),
            preserve_default=False,
        ),
    ]
