# Generated by Django 3.2.22 on 2023-11-18 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0011_book_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(default='contributor', max_length=20)),
                ('city', models.CharField(choices=[('Vienna', 'Vienna'), ('Prague', 'Prague'), ('Dublin', 'Dublin')], max_length=50)),
                ('location', models.CharField(choices=[('by a friend', 'by a friend '), ('to be found', 'to be found')], max_length=20)),
                ('location_hidden', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Czech', 'Czech'), ('German', 'German')], default='English', max_length=10),
        ),
        migrations.DeleteModel(
            name='BookKey',
        ),
        migrations.AddField(
            model_name='bookcontribution',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_contribution', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookcontribution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
